### ISSUE TITLE
Setting scrollwheel option to false possible?

### ISSUE THREAD

**Issue by jonmixnblend** [kalyabin/yii2-select-google-map-location#11]
Hey hey guys.

Firstly, thank you so much for your widget. It works awesomely.

One thing I would love to be able to do easily is set the scrollwheel property in the mapOptions to false, so you don't have the map zooming around as you scroll down the page.

I see in select-google-map-location.js the mapOptions are hard defined on line 22.

Below that there is a a block, 
```
  if (options.onLoadMap) {
            options.onLoadMap(map);
   }
```

If I could hook that call, so one of my functions gets called with the map object, then I could change that option on the fly.

Currently I'm rendering out the form field like:

```
<?= $form->field($model, 'address')->widget(\kalyabin\maplocation\SelectMapLocationWidget::className(), [
    'jsOptions' => ['onLoadMap' => 'customizeGoogleMap'],
    'attributeLatitude' => 'latitude',
    'attributeLongitude' => 'longitude',
    'googleMapApiKey' => getenv('GOOGLE_MAP_API_KEY'),
]);?>
```

Obviously that just passes that function name as a string, which then throws the console error in chrome dev tools, options.onloadMap is not a function.

How could I get that working, or alternatively, could you guys provide a way to set additional mapOptions or override the ones you have set if they are passed in via jsOptions?

Thank you once again.

**Comment by kalyabin** [comment]
Use this code:

```php
$onLoadMap = new \yii\web\JsExpression('customizeGoogleMap');
$form->field($model, 'address')->widget(\kalyabin\maplocation\SelectMapLocationWidget::className(), [
    'jsOptions' => ['onLoadMap' => $onLoadMap],
    'attributeLatitude' => 'latitude',
    'attributeLongitude' => 'longitude',
    'googleMapApiKey' => getenv('GOOGLE_MAP_API_KEY'),
]);
```

**Comment by kalyabin** [comment]
Thank you for your request. I'm sorry that is not answered in time.

**Comment by jonmixnblend** [comment]
@kalyabin Thank you so much for getting back to me on this. Hope you have a great start to the new year:)
