### ISSUE TITLE
required

### ISSUE THREAD

**Issue by asger777** [kalyabin/yii2-select-google-map-location#13]
it has required class itself,but i dont need this input required,i cant delete it,i have search everywhere of widget

**Comment by kalyabin** [comment]
Please provide code snippet wich causes a problem

**Comment by asger777** [comment]
[
![view](https://cloud.githubusercontent.com/assets/23039633/26679244/12bebfc0-4689-11e7-9c44-f8761445017c.jpg)
](url)
its my view code(now i connected via ftp,thats why red error appears-phpstorm)
![api](https://cloud.githubusercontent.com/assets/23039633/26679281/34fb9608-4689-11e7-8d77-2f47797a91d5.jpg)
i have added api code to widget,thats why my view code havent api parameter

![rentacar - axampphtdocsrentacar - selectmaplocationwidget php - phpstorm 2016 3 2](https://cloud.githubusercontent.com/assets/23039633/26679369/96d5ccb8-4689-11e7-9ce0-5c63c848cfa9.jpg)

and at least it is your widget code.

if i have not sent good information,pelase tell me and i will send what you want.

at the end, which variables i accept from view,address,klat and kloc  , all is not required in the model.
but where it comes required ? O.o

**Comment by kalyabin** [comment]
Please provide code snippet with model attributes and model validation
rules.

1 июня 2017 г. 15:19 пользователь "asger777" <notifications@github.com>
написал:
