### ISSUE TITLE
Some error in console

### ISSUE THREAD

**Issue by SerikK** [kalyabin/yii2-select-google-map-location#3]
Hi. After following your guide I had this error in console: Google Maps API error: MissingKeyMapError https://developers.google.com/maps/documentation/javascript/error-messages#missing-key-map-error
Should I change GoogleMapAsset.php?

**Comment by kalyabin** [comment]
Thank you for your request.
Please read new README: https://github.com/kalyabin/yii2-select-google-map-location/blob/master/README.md
